### ISSUE TITLE
Simplify design framework partials

### ISSUE THREAD

**Issue by Dietr** [getchopstick/chopstick#1]
Maybe we should merge the different layers/repo's of the framework in this repo? It will be easier to install and will make maintenance and new features easier to monitor and apply.

**Comment by xavez** [comment]
I agree, this would make more sense, because as mentioned before, the settings file by itself is a dependency for most of the partials anyway. Seeing chopstick SCSS as one package seems like a logical step to me!

**Comment by Dietr** [comment]
Solution:
- [x] Merge all layers into this repo
- [x] Add deprecated in layer repo's
- [x] Create 1 settings file (colors, global, defaults)
